import { Destination, Trip, UserProfile } from '@/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_nirmal',
  name: 'Nirmal Purja',
  email: 'nirmal@globetrotter.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  memberType: 'Pro Member',
  countriesVisited: 12,
  tripsPlanned: 8,
  totalBudgetSpent: 385000,
  bio: 'High-altitude mountaineer & explorer. Always looking for the next ridge to cross.',
  favoriteDestinations: ['Goa, India', 'Tokyo, Japan', 'Kathmandu, Nepal', 'Paris, France'],
};

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest_goa',
    name: 'Goa',
    country: 'India',
    region: 'South Asia',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    description: 'Sun-kissed beaches, Portuguese heritage architecture, and vibrant nightlife.',
    popularActivities: [
      { name: 'Water sports at Calangute Beach', category: 'Adventure', estCost: 2500 },
      { name: 'Sunset Cruise on Mandovi River', category: 'Sightseeing', estCost: 1200 },
      { name: 'Explore Fort Aguada', category: 'Culture', estCost: 500 },
      { name: 'Seafood Tasting at Brittos', category: 'Food', estCost: 1800 },
    ],
    avgCostPerDay: 3500,
    rating: 4.8,
    tags: ['Beach', 'Culture', 'Nightlife', 'Relaxation'],
  },
  {
    id: 'dest_tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'East Asia',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    description: 'Neon-lit skyscrapers, historic temples, pop culture, and world-class ramen.',
    popularActivities: [
      { name: 'Shibuya Crossing & Hachiko Statue', category: 'Sightseeing', estCost: 0 },
      { name: 'Tsukiji Outer Market Food Tour', category: 'Food', estCost: 4500 },
      { name: 'Senso-ji Temple Visit', category: 'Culture', estCost: 600 },
      { name: 'Akihabara Tech & Gaming Crawl', category: 'Entertainment', estCost: 2000 },
    ],
    avgCostPerDay: 8500,
    rating: 4.9,
    tags: ['City', 'Technology', 'Food', 'Culture'],
  },
  {
    id: 'dest_mumbai',
    name: 'Mumbai',
    country: 'India',
    region: 'South Asia',
    coverImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
    description: 'The City of Dreams - colonial landmarks, sea breezes, and Bollywood energy.',
    popularActivities: [
      { name: 'Gateway of India & Elephanta Caves', category: 'Sightseeing', estCost: 1500 },
      { name: 'Marine Drive Evening Stroll', category: 'Nature', estCost: 0 },
      { name: 'Vada Pav & Street Food Trail', category: 'Food', estCost: 600 },
    ],
    avgCostPerDay: 4000,
    rating: 4.7,
    tags: ['City', 'Heritage', 'Food'],
  },
  {
    id: 'dest_paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    description: 'City of Light - legendary art museums, cafe culture, and iconic monuments.',
    popularActivities: [
      { name: 'Eiffel Tower Summit Access', category: 'Sightseeing', estCost: 3500 },
      { name: 'Louvre Museum Masterpieces Tour', category: 'Culture', estCost: 2800 },
      { name: 'Seine River Sunset Dinner Cruise', category: 'Food', estCost: 6500 },
    ],
    avgCostPerDay: 12000,
    rating: 4.9,
    tags: ['Romance', 'Art', 'Culture', 'Luxury'],
  },
  {
    id: 'dest_bengaluru',
    name: 'Bengaluru',
    country: 'India',
    region: 'South Asia',
    coverImage: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80',
    description: 'Silicon Valley of India - lush botanical gardens, craft breweries, and tech hubs.',
    popularActivities: [
      { name: 'Lalbagh Botanical Garden Walk', category: 'Nature', estCost: 200 },
      { name: 'Craft Beer Tasting in Indiranagar', category: 'Food', estCost: 2200 },
      { name: 'Bangalore Palace Tour', category: 'Culture', estCost: 800 },
    ],
    avgCostPerDay: 3200,
    rating: 4.6,
    tags: ['Gardens', 'Food', 'Nightlife'],
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_goa_01',
    title: 'Goa Getaway',
    description: 'Relaxing week of beaches, sea food, water sports, and old Portuguese church exploring.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-10-15',
    endDate: '2026-10-22',
    status: 'Confirmed',
    travelers: 2,
    totalBudget: 45000,
    spentBudget: 28500,
    tags: ['Beach', 'Relaxation', 'Food'],
    destinations: [
      {
        id: 'stop_1',
        cityName: 'Panaji',
        country: 'India',
        startDate: '2026-10-15',
        endDate: '2026-10-18',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
        estimatedCost: 18000,
      },
      {
        id: 'stop_2',
        cityName: 'Palolem',
        country: 'India',
        startDate: '2026-10-18',
        endDate: '2026-10-22',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        estimatedCost: 27000,
      },
    ],
    activities: [
      {
        id: 'act_1',
        title: 'Check-in at Heritage Resort',
        category: 'Accommodation',
        location: 'Fontainhas, Panaji',
        time: '02:00 PM',
        durationMinutes: 60,
        cost: 9000,
        dayNumber: 1,
        dateStr: '2026-10-15',
        completed: true,
      },
      {
        id: 'act_2',
        title: 'Mandovi River Sunset Cruise',
        category: 'Sightseeing',
        location: 'Panaji Jetty',
        time: '05:30 PM',
        durationMinutes: 120,
        cost: 1500,
        dayNumber: 1,
        dateStr: '2026-10-15',
        completed: true,
      },
      {
        id: 'act_3',
        title: 'Parasailing & Jet Skiing',
        category: 'Adventure',
        location: 'Calangute Beach',
        time: '10:00 AM',
        durationMinutes: 180,
        cost: 3500,
        dayNumber: 2,
        dateStr: '2026-10-16',
        completed: false,
      },
      {
        id: 'act_4',
        title: 'Seafood Dinner at Brittos',
        category: 'Food',
        location: 'Baga Beach',
        time: '08:00 PM',
        durationMinutes: 120,
        cost: 2500,
        dayNumber: 2,
        dateStr: '2026-10-16',
        completed: false,
      },
      {
        id: 'act_5',
        title: 'Old Goa Basilica Tour',
        category: 'Culture',
        location: 'Old Goa',
        time: '10:30 AM',
        durationMinutes: 150,
        cost: 600,
        dayNumber: 3,
        dateStr: '2026-10-17',
        completed: false,
      },
    ],
    expenses: [
      { id: 'exp_1', tripId: 'trip_goa_01', title: 'Hotel Booking - 3 Nights', category: 'Accommodation', amount: 15000, date: '2026-10-15' },
      { id: 'exp_2', tripId: 'trip_goa_01', title: 'Flight Tickets (Return)', category: 'Transport', amount: 8500, date: '2026-10-14' },
      { id: 'exp_3', tripId: 'trip_goa_01', title: 'Water Sports Package', category: 'Activities', amount: 3500, date: '2026-10-16' },
      { id: 'exp_4', tripId: 'trip_goa_01', title: 'Beachside Shack Dinner', category: 'Food', amount: 1500, date: '2026-10-15' },
    ],
    smartInsights: [
      {
        id: 'ins_1',
        type: 'tight_margin',
        severity: 'info',
        title: 'Comfortable Schedule',
        message: 'Day 2 activities are well paced with ample break time between parasailing and evening dinner.',
        dayNumber: 2,
      },
    ],
  },
  {
    id: 'trip_japan_02',
    title: 'Japan Adventure',
    description: 'Exploring modern Tokyo, traditional Kyoto temples, and street food in Osaka.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-11-05',
    endDate: '2026-11-19',
    status: 'Planning',
    travelers: 2,
    totalBudget: 180000,
    spentBudget: 110000,
    tags: ['Culture', 'City', 'Food'],
    destinations: [
      { id: 'st_tokyo', cityName: 'Tokyo', country: 'Japan', startDate: '2026-11-05', endDate: '2026-11-10', image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80', estimatedCost: 70000 },
      { id: 'st_kyoto', cityName: 'Kyoto', country: 'Japan', startDate: '2026-11-10', endDate: '2026-11-15', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80', estimatedCost: 60000 },
      { id: 'st_osaka', cityName: 'Osaka', country: 'Japan', startDate: '2026-11-15', endDate: '2026-11-19', image: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=600&q=80', estimatedCost: 50000 },
    ],
    activities: [
      { id: 'act_jp_1', title: 'Shibuya Crossing Walk', category: 'Sightseeing', location: 'Shibuya, Tokyo', time: '10:00 AM', durationMinutes: 90, cost: 0, dayNumber: 1, dateStr: '2026-11-05' },
      { id: 'act_jp_2', title: 'TeamLab Planets Immersive Exhibition', category: 'Entertainment', location: 'Toyosu, Tokyo', time: '02:00 PM', durationMinutes: 180, cost: 3800, dayNumber: 1, dateStr: '2026-11-05' },
      { id: 'act_jp_3', title: 'Fushimi Inari Taisha Shrine Walk', category: 'Culture', location: 'Kyoto', time: '07:30 AM', durationMinutes: 240, cost: 0, dayNumber: 6, dateStr: '2026-11-10' },
    ],
    expenses: [
      { id: 'exp_jp_1', tripId: 'trip_japan_02', title: 'International Flight (Tokyo)', category: 'Transport', amount: 65000, date: '2026-11-01' },
      { id: 'exp_jp_2', tripId: 'trip_japan_02', title: 'JR Shinkansen Train Pass 7-Day', category: 'Transport', amount: 30000, date: '2026-11-02' },
      { id: 'exp_jp_3', tripId: 'trip_japan_02', title: 'Tokyo Hotel Deposit', category: 'Accommodation', amount: 15000, date: '2026-11-03' },
    ],
    smartInsights: [
      {
        id: 'ins_jp_1',
        type: 'schedule_overlap',
        severity: 'warning',
        title: 'Busy Morning on Day 6',
        message: 'Fushimi Inari hike is 4 hours long. Remember to allow time for lunch before afternoon temple visits.',
        dayNumber: 6,
      },
    ],
  },
  {
    id: 'trip_south_03',
    title: 'Southern Soul Search',
    description: 'Heritage trails, tea gardens, backwaters, and coastal culinary delights in South India.',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-12-01',
    endDate: '2026-12-10',
    status: 'Completed',
    travelers: 4,
    totalBudget: 95000,
    spentBudget: 91200,
    tags: ['Nature', 'Heritage', 'Culture'],
    destinations: [
      { id: 'st_kochi', cityName: 'Kochi', country: 'India', startDate: '2026-12-01', endDate: '2026-12-04', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80', estimatedCost: 30000 },
      { id: 'st_munnar', cityName: 'Munnar', country: 'India', startDate: '2026-12-04', endDate: '2026-12-07', image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80', estimatedCost: 35000 },
      { id: 'st_alleppey', cityName: 'Alleppey', country: 'India', startDate: '2026-12-07', endDate: '2026-12-10', image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80', estimatedCost: 30000 },
    ],
    activities: [
      { id: 'act_s_1', title: 'Alleppey Houseboat Overnight Cruise', category: 'Nature', location: 'Alleppey Backwaters', time: '12:00 PM', durationMinutes: 1200, cost: 18000, dayNumber: 7, dateStr: '2026-12-07', completed: true },
      { id: 'act_s_2', title: 'Tea Plantation Trek & Tasting', category: 'Nature', location: 'Munnar Hills', time: '09:00 AM', durationMinutes: 240, cost: 1200, dayNumber: 4, dateStr: '2026-12-04', completed: true },
    ],
    expenses: [
      { id: 'exp_s_1', tripId: 'trip_south_03', title: 'Houseboat Rental', category: 'Accommodation', amount: 18000, date: '2026-12-07' },
      { id: 'exp_s_2', tripId: 'trip_south_03', title: 'Munnar Resort Stay', category: 'Accommodation', amount: 24000, date: '2026-12-04' },
      { id: 'exp_s_3', tripId: 'trip_south_03', title: 'Private SUV Cab across Kerala', category: 'Transport', amount: 28000, date: '2026-12-01' },
      { id: 'exp_s_4', tripId: 'trip_south_03', title: 'Traditional Sadya Feasts & Meals', category: 'Food', amount: 21200, date: '2026-12-05' },
    ],
    smartInsights: [],
  },
];

export const COMMUNITY_TRIPS: Trip[] = [
  {
    id: 'comm_paris_01',
    title: 'Parisian Romance & Art Discovery',
    description: 'A 5-day classic tour of Paris taking in the Eiffel Tower, Louvre, Montmartre, and Seine riverfront dining.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-09-10',
    endDate: '2026-09-15',
    status: 'Confirmed',
    travelers: 2,
    totalBudget: 140000,
    spentBudget: 135000,
    tags: ['Romance', 'Art', 'Food'],
    authorName: 'Sophie Laurent',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    likesCount: 142,
    isPublic: true,
    destinations: [
      { id: 'c_st_paris', cityName: 'Paris', country: 'France', startDate: '2026-09-10', endDate: '2026-09-15', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80', estimatedCost: 140000 },
    ],
    activities: [
      { id: 'c_act_1', title: 'Eiffel Tower Night Illumination', category: 'Sightseeing', location: 'Champ de Mars', time: '08:30 PM', durationMinutes: 120, cost: 3500, dayNumber: 1 },
      { id: 'c_act_2', title: 'Louvre Museum Guided Tour', category: 'Culture', location: 'Rue de Rivoli', time: '10:00 AM', durationMinutes: 240, cost: 2800, dayNumber: 2 },
      { id: 'c_act_3', title: 'Montmartre Artists Square & Sacré-Cœur', category: 'Sightseeing', location: 'Montmartre', time: '03:00 PM', durationMinutes: 180, cost: 0, dayNumber: 3 },
    ],
    expenses: [
      { id: 'c_exp_1', tripId: 'comm_paris_01', title: 'Boutique Hotel in Le Marais', category: 'Accommodation', amount: 75000, date: '2026-09-10' },
      { id: 'c_exp_2', tripId: 'comm_paris_01', title: 'Museum & Attraction Tickets', category: 'Activities', amount: 18000, date: '2026-09-11' },
      { id: 'c_exp_3', tripId: 'comm_paris_01', title: 'Bistro & Cafe Dining', category: 'Food', amount: 42000, date: '2026-09-12' },
    ],
    smartInsights: [],
  },
  {
    id: 'comm_swiss_02',
    title: 'Swiss Alps Hiking & Scenic Trains',
    description: 'Breathtaking train journeys across Zermatt, Interlaken, and Grindelwald with alpine trail walks.',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-08-15',
    endDate: '2026-08-22',
    status: 'Confirmed',
    travelers: 2,
    totalBudget: 220000,
    spentBudget: 215000,
    tags: ['Nature', 'Adventure', 'Scenic'],
    authorName: 'Lukas Weber',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    likesCount: 289,
    isPublic: true,
    destinations: [
      { id: 'c_st_swiss_1', cityName: 'Interlaken', country: 'Switzerland', startDate: '2026-08-15', endDate: '2026-08-18', image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=600&q=80', estimatedCost: 110000 },
      { id: 'c_st_swiss_2', cityName: 'Zermatt', country: 'Switzerland', startDate: '2026-08-18', endDate: '2026-08-22', image: 'https://images.unsplash.com/photo-1572978000104-e35df389b33a?auto=format&fit=crop&w=600&q=80', estimatedCost: 110000 },
    ],
    activities: [
      { id: 'c_act_sw_1', title: 'Jungfraujoch Top of Europe Train', category: 'Adventure', location: 'Grindelwald', time: '08:00 AM', durationMinutes: 360, cost: 18000, dayNumber: 2 },
      { id: 'c_act_sw_2', title: 'Matterhorn Reflection Lake Hike', category: 'Nature', location: 'Zermatt', time: '09:30 AM', durationMinutes: 240, cost: 2500, dayNumber: 5 },
    ],
    expenses: [
      { id: 'c_exp_sw_1', tripId: 'comm_swiss_02', title: 'Swiss Travel Pass Unlimited', category: 'Transport', amount: 80000, date: '2026-08-15' },
      { id: 'c_exp_sw_2', tripId: 'comm_swiss_02', title: 'Alpine Chalet Stays', category: 'Accommodation', amount: 95000, date: '2026-08-15' },
    ],
    smartInsights: [],
  },
];
